server:
  port: 10880

spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/documents
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: update
    generate-ddl: true